text: |
  *<{{workflowRunUrl}}|Workflow _{{workflow}}_ is _{{jobStatus}}_>*

fallback: |-
  [GitHub] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}

fields:
  - title: Job Steps
    value: "{{#each jobSteps}}{{icon this.outcome}} {{@key}}\n{{/each}}"
    short: false
  - title: Workflow
    value: "<{{workflowUrl}}|{{workflow}}>"
    short: true
  - title: Git Ref
    value: "<{{refUrl}}|{{ref}} ({{refType}})>"
    short: true
  - title: Trigger
    value: "{{eventName}}"
    short: true
  - title: Job Status
    value: "{{jobStatus}}"
    short: true
  - title: Version
    value: "{{ env.SERVICE_VERSION }}"
    short: true

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}>

colors:
  success: "good"
  failure: "danger"
  cancelled: "warning"

icons:
  success: ':white_check_mark:'
  failure: ':grimacing:'
  cancelled: ':x:'
  skipped: ':heavy_minus_sign:'
  default: ':interrobang:'

filter:
  steps:
    - build
    - create-release
    - reseed-storage
    - lint
    - test
    - sonar-scan
    - push-image
    - deploy-ec2
    - check-image
    - reseed-database
    - deploy
    - restart
